### ISSUE TITLE
mac微信客户端v2.3.10，appmsg_token字段取消？

### ISSUE THREAD

**Issue by BiterrorChen** [f111fei/article_spider#3]
仅仅填了biz和cookie，输出的错误信息为：
(node:64548) UnhandledPromiseRejectionWarning: Error: Error: {"ret":-3,"errmsg":"no session","cookie_count":1}
    at Step.<anonymous> (/Users/chenchao/article_spider/node_modules/step-pipe/out/index.js:31:27)
    at Generator.throw (<anonymous>)
    at rejected (/Users/chenchao/article_spider/node_modules/step-pipe/out/index.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:64548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by f111fei** [comment]
你可能是查看的 `https://mp.weixin.qq.com/mp/profile_ext?action=home`开头的请求，这个请求是没有appmsg_token的。

chrome里面network查看的请求需要是 `https://mp.weixin.qq.com/mp/profile_ext?action=getmsg` 开头的请求，在历史文章列表里面向下滚动的时候会出现这个请求。

**Comment by BiterrorChen** [comment]
真的谢谢了～解决了
